### ISSUE TITLE
Specifying json output file creates an empty report

### ISSUE THREAD

**Issue by vraravam** [hawkeyesec/scanner-cli#104]
# Issue Template

### Description

I run hawkeye via the npm module (just to remove any configuration/etc issues if running from the docker image. When I run the scan without the `json` flag/configuration-key, it generates a file called `output.json` in the current folder. If I wanted to specify an output file, and use the `--json` command-line switch, or put it in the `.hawkeyerc` config file, the output report *file* is created, but its empty ie only `[]` as the content.

### Steps to Reproduce

1. `hawkeye scan`
2. config file:
```
{
  "failOn": "medium"
}
```
3. With the above, the report is generated as `output.json`
4. Change the config file to:
```
{
  "failOn": "medium"
  "json": "vijay.json"
}
```
5. Run the scan
6. `vijay.json` is created, *but* with the contents only being `[]`

**Expected behavior:** [What you expect to happen]
Same content as in `output.json` should come in the new filename.

**Actual behavior:** [What actually happens]

### Version

1.4.0

### Additional Information

[Any additional information or data that might be necessary to reproduce the issue.]

**Comment by vraravam** [comment]
<bump> Can this be looked at on priority?

**Comment by felixhammerl** [comment]
I am on leave currently, without my machine. I will do that when I am back from vacation. Haven't had the bandwidth due to work and family stuff before that. That being said, the codebase is fairly small, and I am happy for every PR on the project.

**Comment by felixhammerl** [comment]
Sorry, I completely forgot to respond that I have been unable to reproduce the behavior you've reported...

Essentially, even when you're specifying a json file in the hawkeyerc multiple writers via ``--json filename.json``, you're getting the exact same output.
