### ISSUE TITLE
docker build fails due to newer ruby gems requiring ruby 2.3.0

### ISSUE THREAD

**Issue by pb6** [hawkeyesec/scanner-cli#111]
### Description

When running docker build on freshly checked repo, it fails with:
```Step 19/38 : RUN gem install bundler-audit brakeman
 ---> Running in b7a7e5cd85b8
ERROR:  Error installing bundler-audit:
        bundler requires Ruby version >= 2.3.0.
ERROR:  Error installing brakeman:
        brakeman requires Ruby version >= 2.3.0.
```

### Steps to Reproduce

1. docker build -t xyz:latest .

**Expected behavior:** container build to succeed

**Actual behavior:** container build fails

### Version

latest checkout

**Comment by felixhammerl** [comment]
Fixed in the current master
