### ISSUE TITLE
java-owasp scans the whole file tree always

### ISSUE THREAD

**Issue by csokol** [hawkeyesec/scanner-cli#117]
### Description

Even with the flag `all` set to false in the .hawkeyerc, the scanner always scans the whole file tree and not only the files tracked by git. 

### Steps to Reproduce

Running the following script shows the bug:

```bash
rm -rf owasp-bug
mkdir owasp-bug
cd owasp-bug
cat << EOF > .hawkeyerc
{
  "all": false,
  "modules": ["java-owasp"],
  "json": "results.json"
}
EOF
curl https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.1/httpclient-4.1.jar > buggyjar1.jar
touch foo.java
git init
git add .
git commit -m 'msg'
docker run --rm -v $PWD:/target hawkeyesec/scanner-cli:latest > /dev/null
mv results.json 1.json
curl https://repo1.maven.org/maven2/commons-jelly/commons-jelly/1.0/commons-jelly-1.0.jar > buggyjar2.jar
docker run --rm -v $PWD:/target hawkeyesec/scanner-cli:latest > /dev/null
mv results.json 2.json
diff 1.json 2.json
```

**Expected behavior:** there should be no difference between `1.json` and `2.json` because the second jar is not added to git.

**Actual behavior:** there's one more offense in the `2.json` report.

### Version

1.6.0

### Additional Information

The reason why that happens is in [this line](https://github.com/hawkeyesec/scanner-cli/blob/329a13e3d10b01c5bb353fbfad946167a901be0d/lib/modules/java-owasp/index.js#L42). The `-s .` cli param causes dependency-check binary to scan all the files.

I'm not sure how to fix that. One way would be to put each file in a `-s` argument but this might cause the argument list to be too big and exceed the OS limit. We could also consider pass only the jar files as param (and zip's too as dependency-check is able to scan these as well).

This is particularly painful in scala projects that put a some binary stuff in the `project/` subdirectory which is inevitably analyzed by the scanner, making the execution time longer than it could be.

**Comment by felixhammerl** [comment]
Oh, yes that makes sense. Thanks for the report!
