### ISSUE TITLE
Not Windows compatible

### ISSUE THREAD

**Issue by roberthahn8089** [hawkeyesec/scanner-cli#131]
# Issue Template

### Description

The node scanner-cli produces following error on windows:

`[error] Unexpected error occurred! { Error: ENOENT: no such file or directory, scandir 'C:\Users\user\dev\project\C:\Users\user\dev\project\.git'`

### Version

1.6.1

### Additional Information

Line 14 in file-manager.js ``this.targetRegex = new RegExp(`^${this.target}/?`)`` results in `/^C:\Users\user\dev\project\//` but the regex should be `/^C:\\Users\\user\\dev\\project\\?/` to create proper relative path in line 77 `const relativePath = filePath.replace(this.targetRegex, '')`

---------

**Comment by felixhammerl** [comment]
Good point, I do not think that issue came up so far. Thanks for raising the ticket! Might be a good portion of work here, as there are a couple of places, where paths and path separators are hardcoded with `/` delimiter. 

Out of curiosity, git still uses `.git` under windows, correct?

**Comment by roberthahn8089** [comment]
> Out of curiosity, git still uses `.git` under windows, correct?

Yes.
