### ISSUE TITLE
NPM Install fails because of git folder

### ISSUE THREAD

**Issue by nikoWah** [hawkeyesec/scanner-cli#139]
# Issue Template

### Description

Running npm install sometimes fails because of git folder in scanner-cli.
Is it possible to remove this git folder from the npm package?

```
npm ERR! code EISGIT
npm ERR! path /..../node_modules/@hawkeyesec/scanner-cli
npm ERR! git /..../node_modules/@hawkeyesec/scanner-cli: Appears to be a git repo or submodule.
npm ERR! git     /..../node_modules/@hawkeyesec/scanner-cli
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

### Steps to Reproduce

Run npm install

**Expected behavior:** [What you expect to happen]

It should not fail

**Actual behavior:** [What actually happens]

npm install fails 

### Version
1.6.2

### Additional Information
Using post-install or pre-install to remove the git folder does not work in our case.
When we run npm ci on the pipeline, this remove command will throw an error because the node_modules folder will be removed.

**Comment by felixhammerl** [comment]
I am not sure what you mean by it fails "sometimes"? The project contains no submodules or other git modules. It might be that the test fixtures contain something that makes npm trip. 

Can you add what node npm version you're using on your CI?

**Comment by nikoWah** [comment]
Hi
I'm using node v12.5.0 and npm version 6.11.1

**Comment by felixhammerl** [comment]
oooooooooh i see what you're saying. sorry, my bad. the `.git` folder should obviously not be included in the module.

**Comment by felixhammerl** [comment]
Here's what I don't understand. The documentation says that it should never have made it in there.

```
Conversely, some files are always ignored:
* .git
* ...
```

Source: https://docs.npmjs.com/files/package.json#files

**Comment by nikoWah** [comment]
Hmm... yes, that is really weird. Maybe try releasing with the latest npm version. 
Thanks for the awesome module btw.

Looking forward to the next patch release  :)

**Comment by felixhammerl** [comment]
I am very certain this one is to blame on TravisCI. I've investigated it a bit more and look what I found: https://twitter.com/felixhammerl/status/1176912582382366721

**Comment by nikoWah** [comment]
Thanks for making this a priority. Glad you found the issue.

**Comment by M4rk9696** [comment]
I'm facing the same issue in

`node: v10.16.0`
`npm: 6.9.0`

**Comment by M4rk9696** [comment]
Would be happy to help dig into this. I believe Travis CI uses [dpl](https://github.com/travis-ci/dpl) under the hood. I'll look into the [npm provider](https://github.com/travis-ci/dpl/blob/master/lib/dpl/providers/npm.rb) to see if there is anything that could be causing the problem

**Comment by felixhammerl** [comment]
I've added `.git` to the `.npmignore`, which fixes the issue. Frustrating nonetheless. Will make a bugfix release `v1.7.1`.
