### ISSUE TITLE
No such file or directory error when renaming file on CI before Hawkeye

### ISSUE THREAD

**Issue by nicolastrres** [hawkeyesec/scanner-cli#48]
I am using hawkeye on a project's pipeline and one of the things that I am doing on the pipeline before running Hawkeye is renaming a file. So the file name is `ci_config.yml` and I am renaming it to `config.yml`. But I am getting the following error:

```
[info] Running module Credit Card Numbers
fs.js:948
  binding.stat(pathModule._makeLong(path));
          ^
Error: ENOENT: no such file or directory, stat '/target/ci_config.yml'
    at Object.fs.statSync (fs.js:948:11)
    at Object.readFileSync (/hawkeye/lib/util.js:114:21)
    at Object.FileManager.self.readFileSync (/hawkeye/lib/fileManager.js:196:27)
    at Object.FileManager.self.readFile (/hawkeye/lib/fileManager.js:202:28)
    at checkPatternAgainstLanguageFile (/hawkeye/lib/modules/ccnumber/index.js:89:23)
    at /hawkeye/node_modules/async/dist/async.js:3096:16
    at replenish (/hawkeye/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/hawkeye/node_modules/async/dist/async.js:983:17)
    at /hawkeye/node_modules/async/dist/async.js:958:16
    at Immediate._onImmediate (/hawkeye/node_modules/async/dist/async.js:119:16
```
The error is seems to be happening on [this line](https://github.com/Stono/hawkeye/blob/master/lib/modules/ccnumber/index.js#L89) on the ccnumber module.

I think the problem is that hawkeye detected that the file is versioned and put it on the [files object on on the fileManager](https://github.com/Stono/hawkeye/blob/master/lib/fileManager.js#L22), but when the ccnumber module tries to read its content, an error is raised, because the file does not exist anymore (at least with that name).

**Comment by Stono** [comment]
Hey @nicolastrres I actually think this is caused by https://github.com/Stono/hawkeye/blob/master/lib/fileManager.js#L89

As you're in a git repo, hawkeye will be looking at the output from `git ls-tree --full-tree --name-only -r HEAD` but if you've moved a file, it won't be there.  Which obviously isn't great... I'll think about a way to improve this.

You can work around this by using the `hawkeye scan --all` flag, which ignores the git repo.

**Comment by felixhammerl** [comment]
So, good news is that once the current master gets release, at least this won't break your build anymore. Still will crash the module, which is of course not desirable. working on it :)
