### ISSUE TITLE
--fail-on vs hawkeye app error - exit code 1

### ISSUE THREAD

**Issue by pratz** [hawkeyesec/scanner-cli#68]
Its hard to differentiate `exit code 1` between `--fail-on` and hawkeye app error.
For instance, if `.hawkeyerc` isn't configured correctly hawkeye fails with `exit code 1`, in this case its hawkeye app error and not scan errors.
I guess `--fail-on` should support `none` value as well or something similar.

**Comment by ineffyble** [comment]
Or better yet, Hawkeye fails should exit with a non-zero exit code that isn't 1, possibly differing depending severity found?

**Comment by felixhammerl** [comment]
Fixed on master. Have reworked the code pretty much from ground up.

* Unforeseen hawkeye app errors will fail with `42`
* scan findings fail it with `1`
* Modules can fail individually without failing the run. Promises and `async/await` be praised :)

**Comment by pratz** [comment]
Thanks mate 👍
