### ISSUE TITLE
Blacklist modules instead of whitelisting

### ISSUE THREAD

**Issue by ineffyble** [hawkeyesec/scanner-cli#74]
# Blacklist modules instead of whitelisting

### Description

You should be able to specify a specific module (or modules) that should not be used, while allowing every other module to run.

For example, I may not care if my NPM modules are out-of-date, or have a separate means of tracking that. But in order to not have Hawkeye fail due to the `node-npmoutdated` check, I have to include every other module in my `.hawkeyerc`, and even then, any new modules added in future versions of Hawkeye won't be run.

**Comment by felixhammerl** [comment]
Sorry, that npm outdated thingy was my bad. Oops.

Anyway, it makes sense to review the module config, absolutely valid point there.

**Comment by felixhammerl** [comment]
First partial fix: Modules throwing up won't break the run anymore. Woohoo. Fix for ignoring the output is in the pipeline :)
