### ISSUE TITLE
Running the hawkeye analysis by using docker image is throwing TypeError: Invalid Version: undefined

### ISSUE THREAD

**Issue by rhpereda** [hawkeyesec/scanner-cli#93]
I trying to running the hawkeye analisys by using the latest stono/hawkeye docker image in a ReactJS project. But when is executing the step npm outdated --json, i'm getting this error:

[info]  -> npm outdated --json
/hawkeye/node_modules/semver/semver.js:291
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: undefined
    at new SemVer (/hawkeye/node_modules/semver/semver.js:291:11)
    at Function.major (/hawkeye/node_modules/semver/semver.js:563:10)
    at Object.keys.map.forEach (/hawkeye/lib/modules/node-npmoutdated/index.js:37:22)
    at Array.forEach (<anonymous>)
    at options.exec.command (/hawkeye/lib/modules/node-npmoutdated/index.js:34:10)
    at ChildProcess.proc.on.code (/hawkeye/lib/exec.js:56:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

As fas as i understood, this tools only need a package.json file, but when we attempt to running without the node_modules folder this error arise. Once we install all the dependencies by doing "npm install", the scanner run just fine.
The question is: are the node_modules folder required to perform the scan? If not, how can i fix it??

**Comment by felixhammerl** [comment]
Thanks for reaching out and bringing this to our attention! Let me set up a sample project to try and reproduce it.

**Comment by lauraionescu** [comment]
Trying to reproduce this with

```
{
  "name": "packagename",
  "version": "1.1.6",
  "description": "",
  "main": "./index.js",
  "scripts": {
    "test": "jest src",
    "build": "babel src -d lib",
    "start": "webpack-dev-server --config ./webpack.config.js --mode development"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "jest": "^23.4.2",
    "lodash": "4.5.1",
    "moment": "2.11.2",
    "qwest": "~1.5.12",
    "react": "0.14.7",
    "react-dom": "0.14.7",
    "sinon": "^7.0.0",
    "webpack": "^4.16.4",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.5"
  },
  "jest": {
    "testURL": "http://localhost/"
  }
}
```

**Comment by rhpereda** [comment]
Hi there, thanks for the answer, not sure what exactly do you want me to try on?

**Comment by felixhammerl** [comment]
This was a note to myself written from a co-worker's account. Sorry :)

**Comment by lauraionescu** [comment]
@felixhammerl  the issue with the package.json posted above is that it does not have a dependencies section, so it fails at this line:
https://github.com/hawkeyesec/scanner-cli/blob/77b92e303c8af1f5c2b0330f029c8cca1aabdfa9/lib/modules/node-npmoutdated/index.js#L18

It's probably a different issue than the one reported on this thread.

**Comment by hubx** [comment]
Also seeing this on a ReactJS project. If I run `npm outdated` natively (and within the created hawkeye docker container) everything works fine. The projects `package.json` has a `dependencies` section.

**Comment by hubx** [comment]
Found the culprit me and @rhpereda were working with _stono/hawkeye_. Looks like repo here and image were renamed to _hawkeyesec/scanner-cli_ in the last 2 months. Changing to

> docker run --rm -v $PWD:/target hawkeyesec/scanner-cli

works. I still get a `[error] node-npmoutdated returned an error! Invalid Version: undefined` but hawkeye handles this gracefully

Can you add some deprecation warning on the old docker image? 2 moths old does not look suspicious enough to double check the naming.

**Comment by felixhammerl** [comment]
Yes, the graceful failure was introduced in v1.3.0.

Still haven't found the time to look into this, promise to do that later today. I am really sorry for the delay.

**Comment by hubx** [comment]
Nah no pressure, the work around is there. Thanks for working so tirelessly  :)

**Comment by felixhammerl** [comment]
@lauraionescu was right on the money. `Object.assign` has some surprising behavior:

* `Object.assign({}, undefined, {})` returns `{}`
* `Object.assign(undefined, undefined, {})` throws an error.

So, that's that. Fixed this in 244fcbcb705a0db5f193da87db73fa9a2cd90496. Now let me try to fix the other error :)

**Comment by felixhammerl** [comment]
@hubx could you maybe share the package.json and package-lock.json with me? I can't seem to reproduce the Invalid version bug.

**Comment by felixhammerl** [comment]
Oh, and *please* share which version of the scanner, npm, and node you are using. There are quite some contrasts between the node runtimes ...
