### ISSUE TITLE
Node:8 support

### ISSUE THREAD

**Issue by zhenyulin** [hawkeyesec/scanner-cli#95]
# Issue Template

### Description

currently `scanner-cli` requires `node>=10`, while for AWS lambda development environment, it would still be pinned to node:8 at the moment, can we run through test also in node:8 environment and set the engine to >=8?

**Comment by felixhammerl** [comment]
I assume you want to run it for the node v8 lts versions, aka "Carbon". I tend to agree, however the version of `npm` packaged there exhibits quite some problems which are fixed for free in later versions :)

For example, using `npm outdated` in a sample project:

8.9.0:
```
> npm outdated
Package                  Current  Wanted   Latest  Location
@hawkeyesec/scanner-cli  MISSING  linked   linked  packagename
babel-loader               7.1.5   7.1.5    8.0.4  packagename
lodash                     4.5.1   4.5.1  4.17.11  packagename
moment                    2.11.2  2.11.2   2.22.2  packagename
qwest                     1.5.12  1.5.12    4.5.0  packagename
react                     0.14.7  0.14.7   16.6.3  packagename
react-dom                 0.14.7  0.14.7   16.6.3  packagename
```

10.14.1:
```
> npm outdated
Package       Current  Wanted   Latest  Location
babel-loader    7.1.5   7.1.5    8.0.4  packagename
lodash          4.5.1   4.5.1  4.17.11  packagename
moment         2.11.2  2.11.2   2.22.2  packagename
qwest          1.5.12  1.5.12    4.5.0  packagename
react          0.14.7  0.14.7   16.6.3  packagename
react-dom      0.14.7  0.14.7   16.6.3  packagename
```

See how the missing version number in a local package is not a problem anymore?

Let me see if I can work around it, but it might have some funky effects.
